---
- hosts: test
  become: yes
  tasks:

  - name: Add a group called developer
    group:
       name: developer
       state: present
       

  - name: Добавить пользователя 'aduser' 
    user:
      name: aduser
      password: "{{ 'qwerty' | password_hash('sha512') }}"
      shell: /bin/bash
      groups: developer
      append: yes

  - name: Создать 2048-битовый SSH ключ для aduser 
    user:
      name: aduser
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: /home/user1/.ssh/id_ed25519.pub

  - name: Установить authorized key из файла '.ssh/id_ed25519.pub'
    authorized_key:
      user: aduser
      state: present
      key: "{{ lookup('file', '.ssh/id_ed25519.pub') }}"
